AWSTemplateFormatVersion: '2010-09-09'
Description: 'Documents Table and S3 Bucket for UK Home Improvement Platform'

Resources:
  DocumentsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: uk-home-documents
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: projectId
          AttributeType: S
        - AttributeName: userId
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: ProjectIdIndex
          KeySchema:
            - AttributeName: projectId
              KeyType: HASH
          Projection:
            ProjectionType: ALL
        - IndexName: UserIdIndex
          KeySchema:
            - AttributeName: userId
              KeyType: HASH
          Projection:
            ProjectionType: ALL

  DocumentsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: uk-home-documents-bucket
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      VersioningConfiguration:
        Status: Enabled
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256

Outputs:
  DocumentsTableName:
    Description: Name of the Documents DynamoDB table
    Value: !Ref DocumentsTable
  DocumentsBucketName:
    Description: Name of the Documents S3 bucket
    Value: !Ref DocumentsBucket
