AWSTemplateFormatVersion: '2010-09-09'
Description: 'UK Home Improvement Platform - Questionnaire Sessions Table'

Resources:
  QuestionnaireTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: uk-home-questionnaire-sessions
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: projectId
          AttributeType: S
        - AttributeName: userId
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: ProjectIdIndex
          KeySchema:
            - AttributeName: projectId
              KeyType: HASH
          Projection:
            ProjectionType: ALL
        - IndexName: UserIdIndex
          KeySchema:
            - AttributeName: userId
              KeyType: HASH
          Projection:
            ProjectionType: ALL
      Tags:
        - Key: Environment
          Value: production

Outputs:
  QuestionnaireTableName:
    Description: Questionnaire Sessions Table Name
    Value: !Ref QuestionnaireTable
    Export:
      Name: QuestionnaireTable

  QuestionnaireTableArn:
    Description: Questionnaire Sessions Table ARN
    Value: !GetAtt QuestionnaireTable.Arn
    Export:
      Name: QuestionnaireTableArn
